# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Kasun Gamlath
tagline:          'Personal website'
description:      ''
url:              http://www.kasungamlath.com
baseurl:          

author:
  name:           'Kasun Gamlath'
  url:            http://www.kasungamlath.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/kpgx/
